### ISSUE TITLE
f5 does not work with shaders enabled

### ISSUE THREAD

**Issue by Andrews54757** [Andrews54757/OptiFabric-updated#4] opened 2020-08-20 02:38 UTC
Reported by [krozjin](https://www.twitch.tv/krozjin)

Pressing f5 will not work, instead there will be a white screen.

**Comment by amusingimpala75** [comment] 2020-08-20 15:13
Looking at it, the log registers a File not Found when attempting to save the options (may or may not be related), but when the player enters f5 using complementary shaders v2.9, it darkens and adds a random overly. At the same time, the log registers multiple OpenGL errors.
![2020-08-20](https://user-images.githubusercontent.com/69653100/90790582-13f8f300-e2bd-11ea-8b80-c2ef9ed2ec08.png)

**Comment by Andrews54757** [comment] 2020-08-20 15:37
Hmm... If it is an openGL error, there is a possibility that this is an issue with Optifine itself... we may want to test if the error happens in a regular optifine instance.

**Comment by Andrews54757** [comment] 2020-08-20 15:43
It turns out that this is indeed an optifine issue. 

https://github.com/sp614x/optifine/issues/4640

**Comment by amusingimpala75** [comment] 2020-08-20 17:10
I noticed that once the error occurred, entities and particles would not show with or without shaders until the entire game was shut down and restarted.

**Comment by MsWolphie** [comment] 2020-08-25 02:53
Apparently the issue is fixed in recent versions of Optifine?

**Comment by amusingimpala75** [comment] 2020-08-25 03:18
Can confirm, Optifine 1.16.2-pre3 has the f5 bug fixed.

**Closed as completed** 2020-08-25 03:41 UTC
Labels: bug, optifine issue cantfix
